version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo "Compiling your code..."
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Running post-build tasks..."
      - npm test

artifacts:
  files:
    - "**/*"
